language: python
python:
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
install:
  - pip install -r requirements.txt
script:
  - pytest --cov-fail-under=90 --cov=./
after_success:
  - codecov